before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - image_templates:
      - "loderunner/scrt:{{ .Major }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}"
      - "loderunner/scrt:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "loderunner/scrt:latest"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .RawVersion }}-dev-{{ .ShortCommit }}"
