name: scrt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.39-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run linters
        run: golangci-lint run

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Test
        run: go test -race -v ./...

  e2e:
    runs-on: ubuntu-latest
    services:
      minio:
        # Use Bitnami image here because GitHub actions won't let us pass args to docker create
        image: bitnami/minio
        ports:
          - 9000:9000
        volumes:
          - "/tmp/data:/data"
    needs: lint
    steps:
      - name: Create test bucket
        run: mkdir -p /tmp/data/test-bucket
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Test
        env:
          SCRT_TEST_E2E: y
          SCRT_TEST_E2E_S3_ENDPOINT_URL: http://127.0.0.1:9000
          AWS_ACCESS_KEY_ID: minio
          AWS_SECRET_ACCESS_KEY: miniosecret
        run: go test -v ./e2e

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: go build -v .
